### ISSUE TITLE
hi getting this issue when pushing the app to bluemix

### ISSUE THREAD

**Issue by KumarAkshay0506** [IBM-Cloud/cloud-sql-database#1]
TIP: use 'cf logs worldcities --recent' for more information
FAILED

 2018-06-05T19:13:57.90-0500 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2018-06-05T19:13:57.92-0500 [APP/PROC/WEB/0] ERR   File "worldcities.py", line 19, in <module>
   2018-06-05T19:13:57.92-0500 [APP/PROC/WEB/0] ERR     db2info = json.loads(os.environ['VCAP_SERVICES'])['dashDB'][0]
   2018-06-05T19:13:57.92-0500 [APP/PROC/WEB/0] ERR KeyError: 'dashDB'

**Comment by data-henrik** [comment]
Can you do `bx cf env your-app-name`? This obtains the environment information. Assuming you have provisioned the database service in the previous step, it should be visible. It is linked to the app as part of the manifest.yml file. That file assumes you have named the service "sqldatabase".

**Comment by KumarAkshay0506** [comment]
Still facing the same error

System-Provided:
{
 "VCAP_SERVICES": {
  "dashDB For Transactions": [
   {
    "credentials": {
     "db": "BLUDB",
     "dsn": "DATABASE=BLUDB;HOSTNAME=dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net;PORT=50000;PROTOCOL=TCPIP;UID=lhx42445;PWD=bnj64whg3l^gdhn4;",
     "host": "dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net",
     "hostname": "dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net",
     "https_url": "https://dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net",
     "jdbcurl": "jdbc:db2://dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net:50000/BLUDB",
     "password": "bnj64whg3l^gdhn4",
     "port": 50000,
     "ssldsn": "DATABASE=BLUDB;HOSTNAME=dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net;PORT=50001;PROTOCOL=TCPIP;UID=lhx42445;PWD=bnj64whg3l^gdhn4;Security=SSL;",
     "ssljdbcurl": "jdbc:db2://dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net:50001/BLUDB:sslConnection=true;",
     "uri": "db2://lhx42445:bnj64whg3l%5Egdhn4@dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net:50000/BLUDB",
     "username": "lhx42445"
    },
    "label": "dashDB For Transactions",
    "name": "sqldatabase",
    "plan": "Lite",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     "big_data",
     "ibm_created",
     "db2",
     "sqldb",
     "purescale",
     "sql",
     "ibm_dedicated_public",
     "db2 on cloud",
     "db2oncloud",
     "dash",
     "dashdb",
     "oracle",
     "database",
     "transactions",
     "flex",
     "dbaas",
     "lite"
    ],
    "volume_mounts": []
   }
  ]
 }
}

{
 "VCAP_APPLICATION": {
  "application_id": "69fb31b0-e04c-49ae-b9a4-0d9bcc3aa4f8",
  "application_name": "worldcities",
  "application_uris": [
   "worldcities-empathic-tiger.mybluemix.net"
  ],
  "application_version": "9acc7640-adc7-4471-b62d-939f602fe62b",
  "cf_api": "https://api.ng.bluemix.net",
  "limits": {
   "disk": 1024,
   "fds": 16384,
   "mem": 256
  },
  "name": "worldcities",
  "space_id": "3cab9a29-0b89-47df-8e4d-bf32bf3cbaeb",
  "space_name": "dev",
  "uris": [
   "worldcities-empathic-tiger.mybluemix.net"
  ],
  "users": null,
  "version": "9acc7640-adc7-4471-b62d-939f602fe62b"
 }
}


Got this on running the command

**Comment by KumarAkshay0506** [comment]
Getting this error on running the file. 

  2018-06-08T11:09:22.82-0500 [STG/0] ERR You are using pip version 9.0.1, however version 10.0.1 is available.
   2018-06-08T11:09:22.82-0500 [STG/0] ERR You should consider upgrading via the 'pip install --upgrade pip' command.
   2018-06-08T11:09:24.09-0500 [STG/0] ERR You are using pip version 9.0.1, however version 10.0.1 is available.
   2018-06-08T11:09:24.09-0500 [STG/0] ERR You should consider upgrading via the 'pip install --upgrade pip' command.
   2018-06-08T11:09:59.23-0500 [STG/0] OUT Exit status 0
   2018-06-08T11:09:59.23-0500 [STG/0] OUT Staging complete
   2018-06-08T11:09:59.23-0500 [STG/0] OUT Uploading droplet, build artifacts cache...
   2018-06-08T11:09:59.23-0500 [STG/0] OUT Uploading build artifacts cache...
   2018-06-08T11:09:59.23-0500 [STG/0] OUT Uploading droplet...
   2018-06-08T11:10:01.38-0500 [STG/0] OUT Uploaded build artifacts cache (65.1M)
   2018-06-08T11:10:01.53-0500 [API/0] OUT Creating droplet for app with guid 69fb31b0-e04c-49ae-b9a4-0d9bcc3aa4f8
   2018-06-08T11:10:05.02-0500 [STG/0] OUT Uploaded droplet (72.3M)
   2018-06-08T11:10:05.04-0500 [STG/0] OUT Uploading complete
   2018-06-08T11:10:05.13-0500 [STG/0] OUT Stopping instance 6085805c-083c-42dc-b6ce-8d2c0a5082cf
   2018-06-08T11:10:05.13-0500 [STG/0] OUT Destroying container
   2018-06-08T11:10:06.44-0500 [STG/0] OUT Successfully destroyed container
   2018-06-08T11:10:06.78-0500 [CELL/0] OUT Creating container
   2018-06-08T11:10:07.71-0500 [CELL/0] OUT Successfully created container
   2018-06-08T11:10:15.56-0500 [CELL/0] OUT Starting health monitoring of container
   2018-06-08T11:10:16.10-0500 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2018-06-08T11:10:16.10-0500 [APP/PROC/WEB/0] ERR   File "worldcities.py", line 20, in <module>
   2018-06-08T11:10:16.10-0500 [APP/PROC/WEB/0] ERR     db2info = json.loads(os.environ['VCAP_SERVICES'])['dashDB'][0]
   2018-06-08T11:10:16.10-0500 [APP/PROC/WEB/0] ERR KeyError: 'dashDB'
   2018-06-08T11:10:16.14-0500 [APP/PROC/WEB/0] OUT Exit status 1
   2018-06-08T11:10:16.14-0500 [CELL/0] OUT Exit status 0
   2018-06-08T11:10:16.55-0500 [CELL/0] OUT Stopping instance 3f7abbfc-3039-4bfc-5c9a-df2e
   2018-06-08T11:10:16.55-0500 [CELL/0] OUT Destroying container
   2018-06-08T11:10:16.58-0500 [API/0] OUT Process has crashed with type: "web"
   2018-06-08T11:10:16.59-0500 [API/0] OUT App instance exited with guid 69fb31b0-e04c-49ae-b9a4-0d9bcc3aa4f8 payload: {"instance"=>"3f7abbfc-3039-4bfc-5c9a-df2e", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1", "crash_count"=>1, "crash_timestamp"=>1528474216175690278, "version"=>"9acc7640-adc7-4471-b62d-939f602fe62b"}
   2018-06-08T11:10:17.14-0500 [CELL/0] OUT Creating container
   2018-06-08T11:10:17.99-0500 [CELL/0] OUT Successfully destroyed container
   2018-06-08T11:10:18.20-0500 [CELL/0] OUT Successfully created container
   2018-06-08T11:10:23.80-0500 [CELL/0] OUT Starting health monitoring of container
   2018-06-08T11:10:24.19-0500 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2018-06-08T11:10:24.19-0500 [APP/PROC/WEB/0] ERR   File "worldcities.py", line 20, in <module>
   2018-06-08T11:10:24.19-0500 [APP/PROC/WEB/0] ERR     db2info = json.loads(os.environ['VCAP_SERVICES'])['dashDB'][0]
   2018-06-08T11:10:24.19-0500 [APP/PROC/WEB/0] ERR KeyError: 'dashDB'
   2018-06-08T11:10:24.22-0500 [APP/PROC/WEB/0] OUT Exit status 1
   2018-06-08T11:10:24.23-0500 [CELL/0] OUT Exit status 0
   2018-06-08T11:10:24.34-0500 [CELL/0] OUT Stopping instance dad8c7cb-526f-44ba-7c4c-fbdd
   2018-06-08T11:10:24.34-0500 [CELL/0] OUT Destroying container
   2018-06-08T11:10:24.36-0500 [API/0] OUT Process has crashed with type: "web"
   2018-06-08T11:10:24.38-0500 [API/0] OUT App instance exited with guid 69fb31b0-e04c-49ae-b9a4-0d9bcc3aa4f8 payload: {"instance"=>"dad8c7cb-526f-44ba-7c4c-fbdd", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1", "crash_count"=>2, "crash_timestamp"=>1528474224243101411, "version"=>"9acc7640-adc7-4471-b62d-939f602fe62b"}
   2018-06-08T11:10:24.95-0500 [CELL/0] OUT Creating container
   2018-06-08T11:10:25.54-0500 [CELL/0] OUT Successfully destroyed container
   2018-06-08T11:10:28.48-0500 [CELL/0] OUT Successfully created container
   2018-06-08T11:10:37.95-0500 [CELL/0] OUT Starting health monitoring of container
   2018-06-08T11:10:38.92-0500 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2018-06-08T11:10:38.92-0500 [APP/PROC/WEB/0] ERR   File "worldcities.py", line 20, in <module>
   2018-06-08T11:10:38.92-0500 [APP/PROC/WEB/0] ERR     db2info = json.loads(os.environ['VCAP_SERVICES'])['dashDB'][0]
   2018-06-08T11:10:38.92-0500 [APP/PROC/WEB/0] ERR KeyError: 'dashDB'
   2018-06-08T11:10:38.96-0500 [APP/PROC/WEB/0] OUT Exit status 1
   2018-06-08T11:10:38.97-0500 [CELL/0] OUT Exit status 0
   2018-06-08T11:10:39.03-0500 [CELL/0] OUT Stopping instance bda03799-9271-4576-4d6e-b402
   2018-06-08T11:10:39.03-0500 [CELL/0] OUT Destroying container
   2018-06-08T11:10:39.06-0500 [API/2] OUT Process has crashed with type: "web"
   2018-06-08T11:10:39.19-0500 [API/2] OUT App instance exited with guid 69fb31b0-e04c-49ae-b9a4-0d9bcc3aa4f8 payload: {"instance"=>"bda03799-9271-4576-4d6e-b402", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1", "crash_count"=>3, "crash_timestamp"=>1528474239012570800, "version"=>"9acc7640-adc7-4471-b62d-939f602fe62b"}
   2018-06-08T11:10:40.32-0500 [CELL/0] OUT Successfully destroyed container

**Comment by data-henrik** [comment]
Why are you using "Db2 on Cloud" and not "Db2 Warehouse on Cloud" as instructed in the tutorial? They are different services and named differently. The error is caused by that. If you use Db2 on Cloud, you need to change the code.

**Comment by KumarAkshay0506** [comment]
Thank you for the insight.  I will do so and get back to you thank you

**Comment by DeanLiu0521** [comment]
Hello, I have the same error here. And I am using a Lite account. DB2 warehouse on cloud is not accessible to me. How do I need to change the code in this case? Thank you.

**Comment by KumarAkshay0506** [comment]
Please elaborate 
Send a screenshot of the error you find.

Thanks

**Comment by DeanLiu0521** [comment]
Code:
if 'VCAP_SERVICES' in os.environ:
    db2info = json.loads(os.environ['VCAP_SERVICES'])['dashDB'][0]
    db2cred = db2info["credentials"]
    appenv = json.loads(os.environ['VCAP_APPLICATION'])
else:
    raise ValueError('Expected cloud environment')

Error:  
 2018-09-06T12:58:57.37-0400 [CELL/0] OUT Successfully destroyed container
   2018-09-06T13:15:28.30-0400 [CELL/0] OUT Creating container
   2018-09-06T13:15:28.87-0400 [CELL/0] OUT Successfully created container
   2018-09-06T13:15:35.97-0400 [CELL/0] OUT Starting health monitoring of container
   2018-09-06T13:15:36.64-0400 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2018-09-06T13:15:36.65-0400 [APP/PROC/WEB/0] ERR   File "worldcities.py", line 19, in <module>
   2018-09-06T13:15:36.65-0400 [APP/PROC/WEB/0] ERR     db2info = json.loads(os.environ['VCAP_SERVICES'])['dashDB'][0]
   2018-09-06T13:15:36.65-0400 [APP/PROC/WEB/0] ERR KeyError: 'dashDB'
   2018-09-06T13:15:36.68-0400 [APP/PROC/WEB/0] OUT Exit status 1
   2018-09-06T13:15:36.68-0400 [CELL/0] OUT Exit status 0
   2018-09-06T13:15:36.76-0400 [CELL/0] OUT Stopping instance daabab08-4052-4678-7e59-e2ab
   2018-09-06T13:15:36.76-0400 [CELL/0] OUT Destroying container
   2018-09-06T13:15:36.80-0400 [API/3] OUT Process has crashed with type: "web"
   2018-09-06T13:15:36.82-0400 [API/3] OUT App instance exited with guid 99a7e75b-1d3b-414a-b778-93419e1c6f1a payload: {"instance"=>"daabab08-4052-4678-7e59-e2ab", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1", "crash_count"=>10, "crash_timestamp"=>1536254136745416349, "version"=>"f27e5a58-32dc-4ff4-bfda-ea3c1d94d5f5"}
   2018-09-06T13:15:37.88-0400 [CELL/0] OUT Successfully destroyed container


I didn't use the "DB2 Warehouse on cloud" and used "DB2 on Cloud" instead, because of the limitation of my IBM Lite account. Since Henrik said I need to change the code in this case, I didn't find a proper way to change it. Thank you so much if you can help me out. 
![screen shot 2018-09-06 at 2 35 15 pm](https://user-images.githubusercontent.com/12720989/45178045-ac862d80-b1e2-11e8-9305-3c0048ea182c.png)

**Comment by KumarAkshay0506** [comment]
DB2 on cloud will not work on this code since the configurations are set as such.
Also DB2 Warehouse is available free of charge. You just have to enter your Credit Card details for verification purposes.

All the best

**Comment by data-henrik** [comment]
see #2 for a way to use Db2 on Cloud (dashDB for Transactions) in the code. The tutorial is written for Db2 Warehouse on Cloud.
